export interface IFGBuildableGeneratorNuclearJSON {
  ClassName: string
  mCachedLoadPercentage: string
  mOutputInventoryHandlerData: string
  mWasteLeftFromCurrentFuel: string
  mCurrentGeneratorNuclearWarning: string
  mFuelInventoryHandlerData: string
  mFuelClasses: string
  mDefaultFuelClasses: string
  mFuel: MFuel[]
  mAvailableFuelClasses: string
  mFuelResourceForm: string
  mFuelLoadAmount: string
  mRequiresSupplementalResource: string
  mSupplementalLoadAmount: string
  mSupplementalToPowerRatio: string
  mIsFullBlast: string
  mCachedInputConnections: string
  mCachedPipeInputConnections: string
  mPowerProduction: string
  mLoadPercentage: string
  mPowerConsumption: string
  mPowerConsumptionExponent: string
  mDoesHaveShutdownAnimation: string
  mOnHasPowerChanged: string
  mOnHasProductionChanged: string
  mOnHasStandbyChanged: string
  mMinimumProducingTime: string
  mMinimumStoppedTime: string
  mCanEverMonitorProductivity: string
  mCanChangePotential: string
  mMinPotential: string
  mMaxPotential: string
  mMaxPotentialIncreasePerCrystal: string
  mFluidStackSizeDefault: string
  mFluidStackSizeMultiplier: string
  OnReplicationDetailActorCreatedEvent: string
  mInventoryPotentialHandlerData: string
  mEffectUpdateInterval: string
  mDefaultProductivityMeasurementDuration: string
  mLastProductivityMeasurementProduceDuration: string
  mLastProductivityMeasurementDuration: string
  mCurrentProductivityMeasurementProduceDuration: string
  mCurrentProductivityMeasurementDuration: string
  mProductivityMonitorEnabled: string
  mCachedSkeletalMeshes: string
  mAddToSignificanceManager: string
  mSignificanceRange: string
  mTickExponent: string
  mDisplayName: string
  mDescription: string
  MaxRenderDistance: string
  mAlternativeMaterialRecipes: string
  mContainsComponents: string
  mIsConsideredForBaseWeightValue: string
  mBuildEffectSpeed: string
  mAllowColoring: string
  mAllowPatterning: string
  mSkipBuildEffect: string
  mForceNetUpdateOnRegisterPlayer: string
  mToggleDormancyOnInteraction: string
  mIsMultiSpawnedBuildable: string
  mShouldShowAttachmentPointVisuals: string
  mCreateClearanceMeshRepresentation: string
  mCanContainLightweightInstances: string
  mAffectsOcclusion: string
  mOcclusionShape: string
  mScaleCustomOffset: string
  mCustomScaleType: string
  mOcclusionBoxInfo: string
  mAttachmentPoints: string
  mInteractingPlayers: string
  mIsUseable: string
  mHideOnBuildEffectStart: string
  mShouldModifyWorldGrid: string
  mBlueprintBuildEffectID: string
}

interface MFuel {
  mFuelClass: string
  mSupplementalResourceClass: string
  mByproduct: string
  mByproductAmount: string
}
