export interface IFGItemNuclearFuelJSON {
  ClassName: string;
  mSpentFuelClass: string;
  mAmountOfWaste: string;
  mDisplayName: string;
  mDescription: string;
  mAbbreviatedDisplayName: string;
  mStackSize: string;
  mCanBeDiscarded: string;
  mRememberPickUp: string;
  mEnergyValue: string;
  mRadioactiveDecay: string;
  mForm: string;
  mSmallIcon: string;
  mPersistentBigIcon: string;
  mCrosshairMaterial: string;
  mDescriptorStatBars: string;
  mSubCategories: string;
  mMenuPriority: string;
  mFluidColor: string;
  mGasColor: string;
  mCompatibleItemDescriptors: string;
  mClassToScanFor: string;
  mScannableType: string;
  mShouldOverrideScannerDisplayText: string;
  mScannerDisplayText: string;
  mScannerLightColor: string;
  mResourceSinkPoints: string;
}
